### PR TITLE
User model

### PR DESCRIPTION
**Pull request by Alex-Lux**
@KerrynDonovan Can you please review my user model ? :-)

### CODE REVIEW

**Comment by KerrynDonovan** [comment]
Cool- do you want to add validations? (I've got the notes open-)

**Comment by Alex-Lux** [comment]
Hey @KerrynDonovan 
Validations were added, to the user model, can you please review them ?

**Comment by KerrynDonovan** [comment]
Thunderbirds are go!

**Comment by morgatari** [comment]
Let's break things!! 🚀

**Pull request merged**
